# Generated by Django 4.1.1 on 2023-03-09 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('AreaId', models.AutoField(primary_key=True, serialize=False)),
                ('AreaName', models.CharField(max_length=25)),
                ('pinCode', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'Area',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('BlogId', models.AutoField(primary_key=True, serialize=False)),
                ('BlogType', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'BlogCategory',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CatId', models.AutoField(primary_key=True, serialize=False)),
                ('CatName', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('HCId', models.AutoField(primary_key=True, serialize=False)),
                ('HCName', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'HealthCondition',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('OrderDate', models.DateField(auto_now_add=True)),
                ('Amount', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('OrderStatusId', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'OrderStatus',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('PaymentStatusId', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentStatus', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'PaymentStatus',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('PaymentTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentType', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'PaymentType',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleId', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('StateId', models.AutoField(primary_key=True, serialize=False)),
                ('StateName', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'State',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('SubCatId', models.AutoField(primary_key=True, serialize=False)),
                ('SubCatName', models.CharField(max_length=20)),
                ('CatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.category')),
            ],
            options={
                'db_table': 'SubCategory',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('VendorId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Profile', models.ImageField(upload_to='img/vendor')),
                ('Email', models.CharField(max_length=40, unique=True)),
                ('Mobile', models.BigIntegerField(unique=True)),
                ('Password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Vendor',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=25, unique=True)),
                ('UserProfile', models.ImageField(null=True, upload_to='img/users')),
                ('FirstName', models.CharField(max_length=15)),
                ('LastName', models.CharField(max_length=15)),
                ('DOB', models.DateField(default='')),
                ('Gender', models.CharField(max_length=6)),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Mobile', models.BigIntegerField(unique=True)),
                ('Password', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=200)),
                ('otp', models.IntegerField(null=True)),
                ('otp_used', models.IntegerField(null=True)),
                ('AreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.area')),
                ('RoleId', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('SubSubCatId', models.AutoField(primary_key=True, serialize=False)),
                ('SubSubCatName', models.CharField(max_length=20)),
                ('SubCatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.subcategory')),
            ],
            options={
                'db_table': 'SubSubCategory',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('StoreId', models.AutoField(primary_key=True, serialize=False)),
                ('StoreName', models.CharField(max_length=30)),
                ('StoreAddress', models.CharField(max_length=150)),
                ('LicenseNumber', models.IntegerField(default='', unique=True)),
                ('StoreMobile', models.BigIntegerField(default='')),
                ('AreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.area')),
                ('VendorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.vendor')),
            ],
            options={
                'db_table': 'Store',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductImage', models.ImageField(default='media/img/users/1150615.jpg', upload_to='img/products')),
                ('ProductName', models.CharField(max_length=150)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ProductQty', models.IntegerField(default='')),
                ('Description', models.CharField(default='', max_length=1000)),
                ('BestSeller', models.BooleanField()),
                ('Featured', models.BooleanField()),
                ('Trending', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('MRP', models.IntegerField()),
                ('StoreId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.store')),
                ('SubCatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.subcategory')),
                ('SubSubCatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.subsubcategory')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentId', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentAmount', models.IntegerField()),
                ('PaymentDate', models.DateField()),
                ('OrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.order')),
                ('PaymentStatusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.paymentstatus')),
                ('PaymentTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.paymenttype')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.product')),
            ],
            options={
                'db_table': 'OrderItems',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='OrderStatusId',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.orderstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='StoreId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.user'),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('BatchId', models.AutoField(primary_key=True, serialize=False)),
                ('Company', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=20)),
                ('MFG', models.DateField()),
                ('EXPDate', models.DateField()),
                ('Qty', models.IntegerField(default='')),
                ('HCId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.healthcondition')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.product')),
            ],
            options={
                'db_table': 'Medicine',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('FeedBackId', models.AutoField(primary_key=True, serialize=False)),
                ('FeedBackDate', models.DateField()),
                ('FeedBackDesc', models.CharField(max_length=250)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.user')),
            ],
            options={
                'db_table': 'FeedBack',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('CityId', models.AutoField(primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=25)),
                ('StateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.state')),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='CityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsAdminApp.city'),
        ),
    ]
