# Generated by Django 4.1.1 on 2023-03-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicsAdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='PaymentDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
