# Generated by Django 4.1.1 on 2023-04-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicsAdminApp', '0004_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_signature',
        ),
        migrations.RemoveField(
            model_name='product',
            name='StoreId',
        ),
    ]
