from django.urls import path, include
from . import views
urlpatterns = [
   path("",views.index,name='index'),
   path("about/",views.about,name='about'),
   path("login/",views.login,name='login'),
   path("logout/",views.logout,name='logout'),
   path('send_otp/', views.send_otp, name="sendOtp"),
   # path('signup/',views.signup,name="signup"),
   path('accounts/',include('django.contrib.auth.urls')), 
   path("account/",views.account,name='account'),
   path("blogGrid/",views.blockGrid,name='blogGrid'),
   # path("cart/",views.cart,name='cart'),
   path("checkout/",views.checkout,name='checkout'),
   path("contact/",views.contact,name='contact'),
   path("faq/",views.faq,name='faq'),
   path("location/",views.location,name='location'),
   path("orderTracking/",views.orderTracking,name='orderTracking'),
   path("register/",views.client_signup,name='register'),
   path("Shop/",views.Shop,name='shop'),
   path("orderDetails/<int:id>",views.orderDetails,name='shop'),
   path("wishlist/",views.wishlist,name='wishlist'),  
   path("teamDetails/",views.teamDetails,name='teamDetails'),
   path("team/",views.team,name='team'),
   path("appointment/",views.appointment,name='appointment'),
   path("404/",views.fourzerofour,name='404'),
   path("blog/",views.blog,name='blog'),
   path("comingSoon/",views.comingSoon,name='comingsoon'),
   path("service/",views.service,name='service'),
   path("serviceDetails/",views.serviceDetails,name='serviceDetails'),
   path('productDetails/<int:id>',views.ProductDetails,name='productDetails'),
   path('search/', views.search, name='search'),
   path('forgotpassword/',views.forgotpass,name='forgotPassword'),
   path("myprofile/",views.myprofile,name='myprofile'),
   path('set_password/',views.set_password,name="setPass"),
   path('userorder/',views.userorder, name="userOrder"),
   path('shop/<int:id>',views.shopbycat, name="shop"),
   path('u_profile/<int:id>',views.update_profile,name="updateProfile"),
   path('myorder/',views.userorder,name="myOrder"),
   path('placeOrder/',views.place_order,name="PlaceOrder"),
#    path("handlerequest/",views.handlerequest,name='handlerequest'),
   path('invoice/<int:id>',views.invoice,name="invoice"),

   #AddToCart

    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),
    
]
